config/routes.rb
Rails.application.routes.draw do
  	devise_for :users, :controllers => { :registrations => "admins" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	get '/', to: 'site#home'

 	get '/admins/users', to: 'admins#list'

	resources :site

	resources :admins

	resources :tasks

	resources :jobs

	resources :employees

	resources :subcontractors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/employee_log.rb
class EmployeeLog < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :tasks
	has_many :user_jobs 
	has_many :users, through: "user_jobs"
end
	

app/models/task.rb
class Task < ApplicationRecord
	has_many :user_tasks
	has_many :users, through: "user_tasks"
	belongs_to :job

	after_initialize :wat

	def wat
		puts self.name
		puts self.deadline
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_tasks
  has_many :tasks, through: "user_tasks"
  has_many :user_jobs
  has_many :jobs, through: "user_jobs"
  validates :name, presence: true
  validates_confirmation_of :password
end

app/models/user_job.rb
class UserJob < ApplicationRecord
	belongs_to :user
	belongs_to :job 
end

app/models/user_task.rb
class UserTask < ApplicationRecord
	belongs_to :user
	belongs_to :task
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :redirect_if_not_admin 

	# before_filter :create_nav
	# def create_nav
	#   @nav_tabs =  { 
	#   	'Manage' => '/admins'
 #      }
	# end
	
	def index
		@jobs = Job.all
	end

	def new
		@job = Job.new
		@users = User.all
		@user_array = []
		@users.each do |user|
			@user_array.push(user.name)
		end
	end

	def show
		@job = Job.find_by(id: params[:id])
		@tasks = @job.tasks
		

	end
	
	def create
		job = Job.new(
			name: params[:job][:name],
			date: params[:job][:date],
			description: params[:job][:description],
			location: params[:job][:location],
			deadline: params[:job][:deadline]
			)

		if job.save
			#users = []
			params[:job][:users].each do |user|
				#users.push(User.find_by(:name user))
				if user != ''
					job.users << User.find_by(name: user)
				end
			end	
			job.save

			redirect_to '/admins'
		else
			@job = job

			render :new
		end
	end

	def edit
   		@job = Job.find(params[:id])
 		@users = User.all
		@user_array = []
		@users.each do |user|
			@user_array.push(user.name)
    	
    	# redirect_to '/jobs'
    	end
    	render :edit
  	end

  	def update
	job = Job.find(params[:id])
		job.name = params[:job][:name]
		job.date = params[:job][:date]
		job.description = params[:job][:description]
		job.location = params[:job][:location]
		job.deadline = params[:job][:deadline]
		
		if job.save
			# code below prevents duplicate names after updating
			params[:job][:users].each do |name|
				if name != ""
					user = User.find_by(name: name)

					if !job.users.include? user
						job.users << user
					end
				end
			end	
			redirect_to job_path(job.id)
		else
			@job = job

			render :edit
		end
	end

	def destroy
		job = Job.find(params[:id])
   		job.destroy
		redirect_to '/admins'
	end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	





	# def home
		# render :layout => 'employee_layout'
		# if current_user 
		# if current_user.role == "admin"
		# 	redirect_to '/admins'
		# else
		# render :layout => 'employee_layout'
		# render 'home'
		# end
		# end
	# end
end


 	

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 edit_user">
    </br>
    </br>
  

      <h2> Edit <%= @user.name %>'s profile</h2>
      
      <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      <% end %>
      <%= form_for(@user, url: admin_path(@user)) do |f| %>
      <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %><br />
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, :value => @user.encrypted_password, autocomplete: "off", class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, :value => @user.encrypted_password, autocomplete: "off", class: 'form-control' %>
      </div>
      <div class="form-group">
        <label for="sel1">User Role:</label><br>
        <%= f.select :role, ["admin", "employee", "subcontractor"], {}, {include_blank: true, required: 'true', class: 'role form-control'} %>
      </div>
      <div class="actions">
            <button type="submit" class="btn btn-info">Update</button> 
        
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="admin_header"> Admin Page </h2>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div class="container manage-users">
				<div class="row">
					<div class="col-md-5">
						<h2 class="manage-users-header">Manage Users</h2>
					</div>
					<div class="col-md-7">
						<h2 class="create-new-user"><%= button_to("Create New User", new_admin_path, :class => 'btn btn-info btn-sm', method: "get") %></h2>
					</div>
				</div>
				<% ["admin", "employee", "subcontractor"].each do |role| %>
				<h2 class="manage-user-roles"> <%= role.capitalize %> </h2>
				<% @users.each do |user| %>
				<% if user.role == role %>
				
				<div class="row manage-users-user">
					<div class="col-md-5">
						<span><%= link_to user.name, employee_path(user) %> </span>
					</div>
					
					<div class="col-md-7">
						<span class="admin-edit-user">
							<%= button_to("Edit", edit_admin_path(user), :class => 'btn-edit btn btn-info btn-sm', method: "get") %>
						</span>
						<span class="admin-delete-user">
							<%= button_to("Delete", admin_path(user), :class => 'btn btn-info btn-sm', method: "delete") %>
						</span>
					</div>
					<br/>
				</div>
				
				<%end%>
				<% end %>
				<% end %>
			</div>
		</div>
		
		<div class="col-md-6">
			<div class="container manage-jobs">
				<div class="row manage-jobs-with-button">
					<div class="col-md-5 manage-jobs-header-div">
						<h2 class="manage-jobs-header"> Manage Jobs </h2>
					</div>
					<div class="col-md-7">
						
						<h2 class="create-new-job">		<%= button_to("Create New Job", new_job_path, :class => 'btn btn-info btn-sm', method: "get") %></h2>
					</div>
				</div>
				<% @jobs.each do |job| %>
				<div class= "row manage-jobs-job">
					<div class="col-md-6">
						<span> <%= link_to job.name, job_path(job) %> </span>
					</div>
					
					<div class="col-md-6">
						<span class="admin-edit-job">
							<%= button_to("Edit", edit_job_path(job), :class => 'btn-edit btn btn-info btn-sm', method: "get") %>
						</span>
						<span class="admin-delete-job">
							<%= button_to("Delete", job_path(job), :class => 'btn btn-info btn-sm', method: "delete") %>
						</span>
						
					</div>
				</div>
				<%end%>
			</div>
			
		</div>
	</div>
</div>

app/views/admins/list.html.erb
<div class="container">
<div>  
	<h2>Users</h2>
	<% ["admin", "employee", "subcontractor"].each do |role| %>
		<h2> <%= role.capitalize %> </h2>
		<% @users.each do |user| %>
			<% if user.role == role %>
				<%= link_to user.name, admin_path(user) %> | 
				<%= link_to "Delete", admin_path(user), method: "delete" %> | 
				<%= link_to "Edit", edit_admin_path(user), method: "get" %> 
				<br />
			<% end %>
		<%end%>
	<% end %>

	<br/>
	<%= link_to "Create New User", new_admin_path %>
</div>
</div>

app/views/admins/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 create_new_user">
      <br>
      <br>
     
      <h2>Create a New User</h2>
      <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      <% end %>
      
      <%= form_for(@user, url: admins_path) do |f| %>
      <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %><br />
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off", class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
      </div>
      
     


      <div class="form-group">
        <label for="sel1">User Role:</label><br>
        <%= f.select :role, ["admin", "employee", "subcontractor"], {}, {include_blank: true, required: 'true', class: 'form-control'} %>
      </div>
      <div class="actions">
            <button type="submit" class="btn btn-info">Update</button> 
      </div>
      <% end %>
  



  </div>
</div>

</div>

app/views/admins/show.html.erb
<div class="container">

	<h2> Welcome, </h2>
		<%= @user.name %>

	<h2> Current jobsites:</h2>
		<% @jobs.each do |job| %>
			<%= job.name %>

	<h3>Jobs Tasks<h3>
		<% job.tasks.each do |task| %>
		 	<%= task.name %> </br>
		 	<%= task.description %> </br>
			<%= task.deadline %> </br>
		<% end %> 
	 	<% end %> 	
	<button type="button" class="btn btn-info">Info</button>
</div>	

		

	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Halcyon</title>
    <%= csrf_meta_tags %>

    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lalezar|Roboto ', media: 'all', 'data-turbolinks-track': 'reload' %>
<!--     <script src="/assets/jquery.multi-select.js" type="text/javascript" ></script> 
 -->  </head>

 <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
                    
                    <%= link_to "Halcyon Builders", "/", class: "navbar-brand" %> 
               
            </div>
              

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li  >
                      <a id="test" href="#">About</a>
                  </li>
                  <li>
                      <a href="#">Services</a>
                  </li>
                  <li>
                      <a href="#">Contact</a>
                  </li>
<!-- 
                  <% if defined?(@nav_tabs) %>
                      <% @nav_tabs.keys.each do |tab| %>
                        <li>
                          <%= link_to tab, @nav_tabs[tab] %>
                        </li>
                      <% end %>
                   <% end %> 
                </ul>
 -->

                <% if user_signed_in? %> 
                  <% if current_user.role == 'admin' %>
                      <li <% if current_page?(admins_path) %>class="active"<% end %>>
                        <%= link_to 'Manage', '/admins' %>
                      </li>
                      <% elsif current_user.role == 'employee' %>
                         <% puts(current_user.id)%>
                         <li>
                       <%= link_to 'Dashboard', employee_path(current_user) %>
                      </li>
                  <% end %>
                <% end %> 
                </ul>


                <ul class="nav navbar-nav login">
                  <% if user_signed_in? %>
                    <li>
                      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                    </li>
                  <% else %>
                    <li>
                      <%= link_to "Login", new_user_session_path %>
                    </li>
                  <% end %>  
                </ul>
                    
                <!--  -->
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <%= yield %>
  </body>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
      
</html>
    
    

app/views/layouts/employee_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Halcyon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--     <script src="/assets/jquery.multi-select.js" type="text/javascript" ></script> 
 -->  </head>

  <body>

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>