config/routes.rb
Rails.application.routes.draw do
  	devise_for :users, :controllers => { :registrations => "admins" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	get '/', to: 'site#home'

 	get '/admins/users', to: 'admins#list'

	resources :site

	resources :admins

	resources :tasks

	resources :jobs

	resources :employees

	resources :subcontractors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/employee_log.rb
class EmployeeLog < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :tasks
	has_many :user_jobs 
	has_many :users, through: "user_jobs"
end
	

app/models/task.rb
class Task < ApplicationRecord
	has_many :user_tasks
	has_many :users, through: "user_tasks"
	belongs_to :job

	after_initialize :wat

	def wat
		puts self.name
		puts self.deadline
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_tasks
  has_many :tasks, through: "user_tasks"
  has_many :user_jobs
  has_many :jobs, through: "user_jobs"
  validates :name, presence: true
  validates_confirmation_of :password
end

app/models/user_job.rb
class UserJob < ApplicationRecord
	belongs_to :user
	belongs_to :job 
end

app/models/user_task.rb
class UserTask < ApplicationRecord
	belongs_to :user
	belongs_to :task
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :redirect_if_not_admin

	# before_filter :create_nav
	# def create_nav
	#   @nav_tabs =  { 
	#   	'Manage' => '/admins'
 #      }
	# end

	def index
		@users = User.all
		@jobs = Job.all
	end

	def list
		@users = User.all
	end

	def new 
		 @user = User.new
	end

	def create
		user = User.new(
			name: params[:user][:name],
			email: params[:user][:email],
			password: params[:user][:password],
			password_confirmation: params[:user][:password_confirmation],
			role: params[:user][:role]
		)

		if user.save
			redirect_to '/admins'
		else
			@user = user
			render :new
		end
	end

	def show
		if current_user.role == "admin"
			@user = User.find(params[:id])
			@jobs = @user.jobs
			
		else 
		@user = current_user
		@jobs = current_user.jobs

	 end
	end
		
 	def edit
   		@user = User.find(params[:id])
    	render :edit
  	end

  	def update
		user = User.find(params[:id])
		user.name = params[:user][:name]
		user.email = params[:user][:email]
		user.password = params[:user][:password]
		user.password_confirmation = params[:user][:password_confirmation]
		user.role = params[:user][:role]

		if user.save
			redirect_to '/admins'
		else
			@user = user
			render :edit
		end
	end

	def destroy
   		user = User.find(params[:id])
   		user.destroy
    	redirect_to '/admins'
	end
end
		

   	


 

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :redirect_if_not_admin 

	# before_filter :create_nav
	# def create_nav
	#   @nav_tabs =  { 
	#   	'Manage' => '/admins'
 #      }
	# end
	
	def index
		@jobs = Job.all
	end

	def new
		@job = Job.new
		@users = User.all
		@user_array = []
		@users.each do |user|
			@user_array.push(user.name)
		end
	end

	def show
		@job = Job.find_by(id: params[:id])
		@tasks = @job.tasks
		

	end
	
	def create
		job = Job.new(
			name: params[:job][:name],
			date: params[:job][:date],
			description: params[:job][:description],
			location: params[:job][:location],
			deadline: params[:job][:deadline]
			)

		if job.save
			#users = []
			params[:job][:users].each do |user|
				#users.push(User.find_by(:name user))
				if user != ''
					job.users << User.find_by(name: user)
				end
			end	
			job.save

			redirect_to '/admins'
		else
			@job = job

			render :new
		end
	end

	def edit
   		@job = Job.find(params[:id])
 		@users = User.all
		@user_array = []
		@users.each do |user|
			@user_array.push(user.name)
    	
    	# redirect_to '/jobs'
    	end
    	render :edit
  	end

  	def update
	job = Job.find(params[:id])
		job.name = params[:job][:name]
		job.date = params[:job][:date]
		job.description = params[:job][:description]
		job.location = params[:job][:location]
		job.deadline = params[:job][:deadline]
		
		if job.save
			# code below prevents duplicate names after updating
			params[:job][:users].each do |name|
				if name != ""
					user = User.find_by(name: name)

					if !job.users.include? user
						job.users << user
					end
				end
			end	
			redirect_to job_path(job.id)
		else
			@job = job

			render :edit
		end
	end

	def destroy
		job = Job.find(params[:id])
   		job.destroy
		redirect_to '/admins'
	end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	





	# def home
		# render :layout => 'employee_layout'
		# if current_user 
		# if current_user.role == "admin"
		# 	redirect_to '/admins'
		# else
		# render :layout => 'employee_layout'
		# render 'home'
		# end
		# end
	# end
end


 	

app/controllers/tasks_controller.rb
	class TasksController < ApplicationController
		before_action :redirect_if_not_admin 
	




	# def create_nav
	#   @nav_tabs =  { 
	#   	'Manage' => '/admins'
 #      }
	# end
	
	def index
		@tasks = Task.all
		
	end

	def new
		@task = Task.new
		@job_id = params[:job_id]
		@users = User.all
		@user_array = []
		@users.each do |user|
			@user_array.push(user.name)
		end

	end

	def show
		@job_id = params[:job_idx]
		@task = Task.find_by(id: params[:id])
		@task_users = @task.users
	end
	

	def create
		job_id = params[:task][:job_id]
		@task = Task.new(
			name: params[:task][:name],
			date: params[:task][:date],
			description: params[:task][:description],
			location: params[:task][:location],
			deadline: params[:task][:deadline],
			# user: params[:task][:user],
			job_id: job_id
			)

		
		if @task.save
			
			params[:task][:users].each do |user|
				#users.push(User.find_by(:name user))
				if user != ''
					@task.users << User.find_by(name: user)
				end
			end	
			redirect_to '/jobs/' + job_id
			#render plain: params[:task][:date]

		else
			render :new
		end
		
	end


	def edit
   		@task = Task.find(params[:id])
 		users = User.all
		@users = []

		users.each do |user|
			@users.push(user.name)
    	# redirect_to '/jobs'
    	end

    	@task_users = []
    	@task.users.each do |user|
    		@task_users.push(user.name)

    	end

    	render :edit
  	end

  	def update
		task = Task.find(params[:id])
		task.name = params[:task][:name]
		task.date = params[:task][:date]
		task.description = params[:task][:description]
		task.location = params[:task][:location]
		task.deadline = params[:task][:deadline]

		job_id = task.job.id
		job = Job.find(job_id)

		if task.save
			task.users.destroy_all
			params[:task][:users].each do |name|
				if name != ""
					user = User.find_by(name: name)

					if !task.users.include? user
						task.users << user
					end
				end
			end	
			redirect_to job_path(job_id)
		else
			@task = task

			render :edit
		end
	end

	def destroy
   		task = Task.find(params[:id])
   	
   		task.destroy
   		job_id = task.job.id
   		redirect_to job_path(job_id)
	end

end


    	







			

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :redirect_if_not_admin 

	def index
		@users = User.all
	end

	def new 
		 @user = User.new
	end

	def create
		user = User.new(
			name: params[:user][:name],
			email: params[:user][:email],
			password: params[:user][:password]
		)

		if user.save
			redirect_to '/admins'
		else
			@user = user

			render :new
		end
	end

 	def edit
   		@user = User.find(params[:id])
 
    	render :edit
  	end

  	def update
		user = User.find(params[:id])
		user.name = params[:user][:name]
		user.email = params[:user][:email]
		user.password = params[:user][:password]

		if user.save
			redirect_to '/admins'
		else
			@user = user

			render :edit
		end
	end

	def destroy

   		user = User.find(params[:id])
   	
   		user.destroy

    	redirect_to admins_path
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 edit_job">
      <br>
  
     
      <div class="container">
        <h2> Edit <%= @task.name %> </h2>
        <%= form_for(@task, url: task_path(@task)) do |f| %>
        <div class="form-group">
          <%= f.label :name %><br />
          <%= f.text_field :name, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :date %><br />
          <%= f.datetime_field :date, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :location %><br />
          <%= f.text_field :location, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :deadline %><br />
          <%= f.datetime_field :deadline, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, class: 'form-control'  %>
        </div>
        <div class="field">
          <%= f.label :employees %><br />
        </div>
          
        <%= f.select :users, options_for_select(@users, @task_users), {}, {:multiple => true} %>
        
        <div class="actions">
          <button type="submit" class="btn btn-info">Update</button> 
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
$('#task_users').multiSelect({ keepOrder: true });
</script>

app/views/tasks/index.html.erb
<div class="container">
	<h2> Tasks Page </h2>


	<% @tasks.each do |task| %>
		<%= link_to task.name, task_path(task) %> | 
		<%= link_to "Delete", task_path(task), method: "delete" %> | 
		<%= link_to "Edit", edit_task_path(task), method: "get" %> 
		<br />

	<%end%>

	<br>


	<%= link_to "Create a new task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 edit_job">
      <br>
      <div class="container">
        <h2>Create Task</h2>
        
        <%= form_for(@task, url: tasks_path) do |f| %>
        
        <div class="field">
          
          <%= f.hidden_field :job_id, :value => @job_id %>
        </div>
        <div class="form-group">
          <%= f.label :name %><br />
          <%= f.text_field :name, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :date %><br />
          <%= f.datetime_field :date, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :location %><br />
          <%= f.text_field :location, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :deadline %><br />
          <%= f.datetime_field :deadline, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, class: 'form-control'  %>
        </div>
        <div class="field">
          <%= f.label :employee %><br />
          
        </div>
        <%= f.select :users, options_for_select(@user_array), {}, {:multiple => true} %>
        
        <div class="actions">
     
          <button type="submit" class="btn btn-info">Create</button> 
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
$('#task_users').multiSelect({ keepOrder: true });
</script>

app/views/tasks/show.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Halcyon Builders</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
                 <ul class="nav navbar-nav login">
                 	<li>
                    	<%= link_to "Login", new_user_session_path %>
                    </li>
                    
            	  <!--  -->
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>




<div class="container">
	<h2> Task details page </h2>

	<h3> <%= @task.name %> </h3>

	<ul>
		<li> Date: <%= @task.date %> </li>
		<li> Location: <%= @task.location %> </li>
		<li> Description: <%= @task.description %> </li>
		<li> Deadline: <%= @task.deadline %> </li>
			<%= @users.each do |user| %>
		<li> Employee: <%=user.name %> </li>
			<% end %>
	</ul>
</div>