config/routes.rb
Rails.application.routes.draw do
  	devise_for :users, :controllers => { :registrations => "admins" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	get '/', to: 'site#home'

 	get '/admins/users', to: 'admins#list'

	resources :site

	resources :admins

	resources :tasks

	resources :jobs

	resources :employees

	resources :subcontractors
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :tasks
	has_many :user_jobs 
	has_many :users, through: "user_jobs"
end
	

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :redirect_if_not_admin 

	# before_filter :create_nav
	# def create_nav
	#   @nav_tabs =  { 
	#   	'Manage' => '/admins'
 #      }
	# end
	
	def index
		@jobs = Job.all
	end

	def new
		@job = Job.new
		@users = User.all
		@user_array = []
		@users.each do |user|
			@user_array.push(user.name)
		end
	end

	def show
		@job = Job.find_by(id: params[:id])
		@tasks = @job.tasks
		

	end
	
	def create
		job = Job.new(
			name: params[:job][:name],
			date: params[:job][:date],
			description: params[:job][:description],
			location: params[:job][:location],
			deadline: params[:job][:deadline]
			)

		if job.save
			#users = []
			params[:job][:users].each do |user|
				#users.push(User.find_by(:name user))
				if user != ''
					job.users << User.find_by(name: user)
				end
			end	
			job.save

			redirect_to '/admins'
		else
			@job = job

			render :new
		end
	end

	def edit
   		@job = Job.find(params[:id])
 		@users = User.all
		@user_array = []
		@users.each do |user|
			@user_array.push(user.name)
    	
    	# redirect_to '/jobs'
    	end
    	render :edit
  	end

  	def update
	job = Job.find(params[:id])
		job.name = params[:job][:name]
		job.date = params[:job][:date]
		job.description = params[:job][:description]
		job.location = params[:job][:location]
		job.deadline = params[:job][:deadline]
		
		if job.save
			# code below prevents duplicate names after updating
			params[:job][:users].each do |name|
				if name != ""
					user = User.find_by(name: name)

					if !job.users.include? user
						job.users << user
					end
				end
			end	
			redirect_to job_path(job.id)
		else
			@job = job

			render :edit
		end
	end

	def destroy
		job = Job.find(params[:id])
   		job.destroy
		redirect_to '/admins'
	end

end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 edit_job">
      </br>
    
      
      <h2> Edit <%= @job.name %> </h2>
      <%= form_for(@job, url: job_path(@job)) do |f| %>
      <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :date %><br />
        <%= f.datetime_field :date, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :location %><br />
        <%= f.text_field :location, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :deadline %><br />
        <%= f.datetime_field :deadline, class: 'form-control' %>
       <div class="form-group">
        <%= f.label :description %><br />
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      </div>
      <div class="field">
        <%= f.label :Employees %><br />
      </div>
      
      
      <%= f.select :users, options_for_select(@user_array), {}, {:multiple => true} %>
      <div class="actions">
        
          <button type="submit" class="btn btn-info">Update</button> 
      </div>
      <% end %>
    </div>
  </div>
</div>
<script>
$('#job_users').multiSelect({ keepOrder: true });
</script>

app/views/jobs/index.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Halcyon Builders</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
                 <ul class="nav navbar-nav login">
                 	<li>
                    	<%= link_to "Login", new_user_session_path %>
                    </li>
                    
            	  <!--  -->
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>





<div class="container">
	<h2> Jobs </h2>
		<% @jobs.each do |job| %>
		<%= link_to job.name, job_path(job) %> | 
		<%= link_to "Delete", job_path(job), method: "delete" %> | 
		<%= link_to "Edit", edit_job_path(job), method: "get" %> |
		
		<br/>

	<%end%>

	<br>


	<%= link_to "Create a New Job", new_job_path %>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 edit_user">
      </br>
      <div class="container">
        <h2>Create a New Job</h2>
        
        <%= form_for(@job, url: jobs_path) do |f| %>
        <div class="form-group">
          <%= f.label :name %><br />
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :date %><br />
          <%= f.datetime_field :date, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :location %><br />
          <%= f.text_field :location, class: 'form-control' %>
        </div>
         <div class="form-group">
          <%= f.label :deadline %><br />
          <%= f.datetime_field :deadline, class: 'form-control' %>
        </div>
         <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="field">
        
          <%= f.label :employee %><br />
          
        </div>
        <%= f.select :users, options_for_select(@user_array), {}, {:multiple => true} %>
        <div class="actions">
          <button type="submit" class="btn btn-info">Create</button> 
        </div>
        
        <% end %>
      </div>
    </div>
  </div>
  <script>
  $('#job_users').multiSelect({ keepOrder: true });
  </script>
        

app/views/jobs/show.html.erb
<div class="container job_panel">
  <h3 class="job_title">Job </h3>
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title"><%= @job.name %></h3>
	  </div>
	  <div class="panel-body">
			<p> Date: <%= @job.date %></p>
			<p> Location: <%= @job.location %> </p>
			<p> Description: <%= @job.description %> </p>
			<p>Employees:
				<% @job.users.each do |user| %>
					 <%= user.name %>,
				<% end %>
				</p>	
	  </div>
	</div>
</div>
	
	   

<div class="container task_panel">
<h3>Tasks</h3>
<%counter=1%>
<!-- <ul> -->
	<% @tasks.each do |task| %>
	<!-- <li> -->
	<div class="panel-group " id="accordion" role="tablist" aria-multiselectable="true">
	  <div class="panel panel-default">
	    <div class="panel-heading" role="tab" id="headingOne">
	      <h4 class="panel-title">
	        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#<%=counter%>" aria-expanded="true" aria-controls="collapseOne">
	          <%= task.name %>
	        </a>
	      </h4>
	    </div>
	    <div id="<%=counter%>" class="panel-collapse collapse out" role="tabpanel" aria-labelledby="headingOne">
	   		<div class="panel-body">
       			<p>Date: <%= task.date %> </p>
				<p>Location: <%= task.location %> </p>
				<p>Description: <%= task.description %> </p>
				<p>Deadline: <%= task.deadline%> </p>
				<p>Employees:
				<% task.users.each do |user| %>
					 <%= user.name %>,
				<% end %>
				</p>	
				<%= link_to "Edit", edit_task_path(task), method: "get" %> |						
				<%= link_to "Delete", task_path(task), method: "delete" %> |  	
      		</div>
	    </div>
	  </div>
	</div>
	<!-- </li> -->
	<%counter+=1%>
	<% end %>
<!-- </ul> -->

	<form method="get" action="/tasks/new">
	  <input type="hidden" name="job_id" value="<%= @job.id%>"> <br>
		<button type="submit" class="btn btn-info">Create New Task</button>			
 	<!-- 	 <button>Create New Task</button>  -->
	</form>
</div>
			